Release v6.0.2 lacework-agent Helm Charts
lacework/helm-charts pull request #110
Opened 2022-09-24 00:53 UTC by nschmeller

Signed-off-by: nschmeller <nick.schmeller@lacework.net>

2022-09-24 01:05 UTC, cirego requested changes
Nick, it looks like the pod label change is missing. I would have expected that this PR mostly updated the image tag / chart version and nothing else.

2022-09-24 05:23 UTC, joebowbeer commented on lacework-agent/templates/daemonset.yaml
>          name: {{ include "lacework-agent.name" . }}
```suggestion
        name: {{ include "lacework-agent.name" . }}
        {{- with .Values.laceworkConfig.labels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
```

2022-09-24 05:32 UTC, joebowbeer commented on lacework-agent/templates/daemonset.yaml
> -        {{- with .Values.laceworkConfig.labels }}
regression

2022-09-24 05:33 UTC, joebowbeer commented on lacework-agent/values.schema.json
> +                "scrapeIntervalMins"
```suggestion
                "enable"
```

regression

2022-09-24 05:35 UTC, joebowbeer commented
should be no changes to daemonset or schema

2022-09-26 17:24 UTC, cirego approved these changes
Nice! Thank you Nick!

2022-09-26 19:03 UTC, merged